#!/bin/bash

variant=""
jorbs=16
image="us-docker.pkg.dev/sysdig-artifact-registry-dev/gar-docker/agent/agent-linux-builder:latest-x86_64"
while [[ $# -gt 0 ]]; do
	opt="$1"
	shift

	case $opt in
	-j|--jobs)
		jorbs="$1"
		shift
		;;
	-l|--local)
		image="agent-linux-builder:latest-x86_64"
		shift
		;;
	-b|--builder)
		image="$1"
		shift
		;;
	*)
		variant="$variant $opt" # concat
		;;
	esac
done

if [ -z "$variant" ]; then
	variant="make install"
fi

cmd="docker run --rm -it --name agent-build -e MAKE_JOBS=$jorbs \
	-e CMAKE_C_COMPILER_LAUNCHER=sccache \
	-e CMAKE_CXX_COMPILER_LAUNCHER=sccache \
	-v /draios/build/sccache:/root/.cache/sccache
	-v /draios/agent:/draios/agent:ro \
	-v /opt/draios:/opt/draios \
	-v /opt/draios/pkgs:/out \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v /draios/build/agent:/code/agent/build \
	-v pipcache:/root/.cache \
	$image $variant"
echo $cmd
$cmd

echo Done!
notify-send "Your build" "is done"

